using UnityEngine;

namespace PurrNet.Voice
{
    public abstract class OutputProvider : MonoBehaviour
    {
        /// <summary>
        /// The Voice Output that'll be generated by the Output provider.
        /// </summary>
        public abstract IVoiceOutput output { get; }
        
        /// <summary>
        /// Used to initialize the output provider with the necessary context
        /// </summary>
        /// <param name="inputSource">Where the audio data will be coming from</param>
        /// <param name="processSamples">The delegate for processing samples</param>
        /// <param name="levels">The filter level at which to be handling filtering</param>
        public abstract void Init(IAudioInputSource inputSource, ProcessSamplesDelegate processSamples = null, params FilterLevel[] levels);

        /// <summary>
        /// Allows easy modifying of input device
        /// </summary>
        /// <param name="input">New input device to change to</param>
        public abstract void SetInput(IAudioInputSource input);
    }
}
